package graviton.runtime.metrics

object MetricKeys:
  val BytesIngested                = "graviton_bytes_ingested"
  val BlocksIngested               = "graviton_blocks_ingested"
  val ScanOutputs                  = "graviton_ingest_scan_outputs"
  val UploadDuration               = "graviton_upload_duration_seconds"
  val BackendFailures              = "graviton_backend_failures_total"
  val BackendOperationsTotal       = "graviton_backend_operations_total"
  val BackendOperationDuration     = "graviton_backend_operation_duration_seconds"
  val BackendBytesTransferredTotal = "graviton_backend_bytes_transferred_total"
  val BackendMaintenanceTotal      = "graviton_backend_maintenance_total"
  val BlobOperationsTotal          = "graviton_blob_operations_total"
  val BlobOperationFailuresTotal   = "graviton_blob_operation_failures_total"
  val BlobOperationDuration        = "graviton_blob_operation_duration_seconds"
  val BlobIngestsTotal             = "graviton_blob_ingests_total"
  val BytesIngestedTotal           = "graviton_bytes_ingested_total"
  val FreshBlocksTotal             = "graviton_fresh_blocks_total"
  val DuplicateBlocksTotal         = "graviton_duplicate_blocks_total"
  val HttpRequestsTotal            = "graviton_http_requests_total"
  val HttpErrorsTotal              = "graviton_http_errors_total"
  val HttpLatencySeconds           = "graviton_http_request_duration_seconds"
  val UploadLocalityDecisionsTotal = "graviton_upload_locality_decisions_total"
  val UploadLocalityFailuresTotal  = "graviton_upload_locality_failures_total"
  val UploadHotStateEntries        = "graviton_upload_hot_state_entries"
  val ShardcakeHealthChecksTotal   = "graviton_shardcake_health_checks_total"
  val ShardcakeHealthDuration      = "graviton_shardcake_health_check_duration_seconds"
  val ShardcakeReady               = "graviton_shardcake_ready"
  val ShardcakeAssignedShards      = "graviton_shardcake_assigned_shards"
  val ShardcakeLocalAssignedShards = "graviton_shardcake_local_assigned_shards"
  val ShardcakeObservedNodes       = "graviton_shardcake_observed_nodes"
  val ShardcakeTrackedSessions     = "graviton_shardcake_tracked_sessions"
