name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '17'
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Build website (zio-sbt)
        run: |
          sbt docs/clean
          sbt docs/mdoc
          sbt docs/buildWebsite
      - name: Prepare Pages artifact
        run: |
          mkdir -p site
          cp -r docs/target/site/* site/ 2>/dev/null || true
          touch site/.nojekyll
          [ -f site/index.html ] || echo '<!doctype html><meta charset="utf-8"><title>Graviton Docs</title><h1>Graviton Documentation</h1><p><a href="./index.md">Open docs/index.md</a></p>' > site/index.html
          cp site/index.html site/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
