name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Build docs
        run: |
          ./sbt docs/mdoc doc
          mkdir -p site
          cp -r docs/target/mdoc/* site/
          for d in modules/*/target/scala-*; do
            name=$(basename "$(dirname "$(dirname "$d")")")
            if [ -d "$d/api" ]; then
              cp -r "$d/api" "site/$name"
            fi
          done
      - name: Add Pages essentials (.nojekyll, index.html, 404.html)
        run: |
          touch site/.nojekyll
          if [ ! -f site/index.html ]; then
            cat > site/index.html << 'EOF'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Graviton Docs</title>
    <style>
      body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"; margin: 2rem auto; max-width: 900px; padding: 0 1rem; line-height: 1.6; }
      h1 { margin-bottom: 0.5rem; }
      .note { color: #555; }
      ul { padding-left: 1.25rem; }
      a { color: #0b5fff; text-decoration: none; }
      a:hover { text-decoration: underline; }
      code { background: #f6f8fa; padding: 0.125rem 0.25rem; border-radius: 4px; }
    </style>
  </head>
  <body>
    <h1>Graviton Documentation</h1>
    <p class="note">Project site is published from generated docs. If you see this placeholder, the Markdown output was uploaded without a static site generator. Browse the Markdown entry point below:</p>
    <ul>
      <li><a href="./index.md">Open docs/index.md</a></li>
    </ul>
  </body>
  </html>
EOF
          fi
          cp site/index.html site/404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
